### ISSUE TITLE
Add support for other regions

### ISSUE THREAD

**Issue by alexrp** [alexrp/alkahest#7]
- [x] JP
- [x] KR
- [x] RU
- [x] TW

**Comment by alexrp** [comment]
TW support added in 5c9f86230a04e87d6ac72ded2a22f6514975f4c6.

**Comment by alexrp** [comment]
KR support added in 4e5851f6d39ca179e81ef49440bf65c5856682b7.

**Comment by alexrp** [comment]
RU support added in 92fe46b391c0785a767693095d4fad8590b77d08.

**Comment by alexrp** [comment]
JP support added in 1e193c605a5cf4159bd114a482a7dbc063fd357a.

**Comment by Every-L** [comment]
Just for your info, on k-tera, if you are setting the server, both ways are successfully worked.

1. Launch the launcher before I executing exe file, and while the picture of Valkyrie is on, launched the exe file. No error, successfully fetch everything from launcher and so on.
2. After opening the tera, before choosing the server, launching the exe file. Works as well.

Thanks for developing this, I am playing k-tera from US, and was struggling with rapid fire and such. Plug-in for skill-prediction-master would be appreciated.

P.S. skill prediction github address : https://github.com/pinkipi/skill-prediction

**Comment by alexrp** [comment]
@Every-L Are you sure that the game is actually connecting through Alkahest? You should see something like this:

![image](https://cloud.githubusercontent.com/assets/44076/24777657/b340786e-1b26-11e7-8626-eafb3f5552b2.png)

Last time I asked someone to try Alkahest on KTERA, it did not work due to the PIN input thing for some reason.

> Plug-in for skill-prediction-master would be appreciated.

Unfortunately, such plugins are huge undertakings as they require extensive in-game testing. I think @pinkipi has spent literally hundreds of hours on SP. I just don't have the spare time to take on a project like that. Hopefully somebody out there will feel like writing a similar plugin for Alkahest.

**Comment by Every-L** [comment]
@alexrp Yes, I am seeing that kind of screen and 2 plugins are attached on K-tera
I can take a screenshot if I arrive home, sadly I do not have a visual studio to build the source code on my laptop. Or if you do not mind posting a built file on the google drive, I would test out and post the screenshot here.

For the plugin, I actually skimmed through it, I have very basic programming knowledge (mostly c). 
I was wondering if it is possible to tweak pinkipi's code to put it on the plugin. Because I think alkahest is more window user friendly compare to tera-proxy. However, as I mentioned, my lacking knowledge on programming is the issue.

**Comment by alexrp** [comment]
Here is a build of current master configured for KR: https://www.dropbox.com/s/s88xvf3sj64arpp/alkahest_kr.zip?dl=0

**Comment by Every-L** [comment]
![image](https://cloud.githubusercontent.com/assets/26956853/24787077/fb9552bc-1b1a-11e7-8f13-b95e679e7fd7.png)

Here's k-tera result

**Comment by alexrp** [comment]
@Every-L Great! So, just to be clear, you're doing the following:

1. Log in via KTERA website.
2. Start TERA launcher.
3. Start Alkahest.
4. Start TERA.

And then it just works?

Also, do you have the PIN security thing enabled on your account?

**Comment by Every-L** [comment]
No, you can actually make it work before the server list is on
1. Log in via KTera website
2. Start Tera launcher
3. Press Start button
4. Right before the tera exe comes on, launch the alkahest (Valkirie image)
5. log into server

Yes I have the 4 digit PIN security enabled on my account.
The skyblue line comes on right before the server list is refreshed.
And following three lines comes on when I logged into server.

**Comment by alexrp** [comment]
OK, then I think KR support is in a good enough state to declare it done. I'll add some notes to [README.md](README.md) about it.
